### PR TITLE
Fixes bug 1125862 - Removed paireduuid service and associated webapp bits.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
r? @peterbe or @selenamarie

### CODE REVIEW

**Comment by rhelmer** [comment]
Note that ```reports_clean``` has an hour delay versus ```reports``` which gets crashes inserted real-time.

If this matters, we could use the ```processed_crashes``` table instead, or fetch the crash from S3.

**Comment by peterbe** [comment]
I guess it looks fine. I'm just not clued up enough on this at the moment. I think @selenamarie should review this instead.

**Comment by AdrianGaudebert** [comment]
I don't think the 1 hour delay matters much, this is used by the report/index page to show just a small information about crashes. And it's much simpler to change the code to use reports_clean than processed_crashes. :)

**Comment by selenamarie** [comment]
@AdrianGaudebert individual reports will fail to display if we implement this change because we filter out duplicate reports, which have different UUIDs. We either need to fetch them from `processed_crashes` or find the filtered out crashes in `reports_duplicates` and display only the rows that the crash has in common. I'd guess the proper way of handling this is: 
```
   SELECT duplicate_of as uuid from reports_duplicates where uuid = 'xxx'
```
And if we do find the value in this table, we then use the 'duplicate_of' value instead of `uuid` for filling in the rest of the values.

Briefly, something like: 

```
with duplicate as (
   SELECT 'xxx' as uuid, duplicate_of as dupe from reports_duplicates where uuid = 'xxx'
), 
with original as (
   SELECT uuid from reports_clean where uuid = 'xxx'
)
SELECT coalesce(duplicate.dupe, original.uuid)
FROM duplicate JOIN original USING uuid
...
```

**Comment by selenamarie** [comment]
Another option would be to fetch metadata for a crash from a different crashstorage backend (s3?).

**Comment by AdrianGaudebert** [comment]
Good news, everyone! This service is not used anymore! This is now a PR to remove it entirely. :-)

**Comment by phrawzty** [comment]
good news everyone

**Comment by peterbe** [comment]
rebase?

**Pull request merged**
