### PR TITLE
Fixes bug 1361308 - Display thread names of the crashing stacks.

### PR DESCRIPTION
**Pull request by CervantesYu**
This displays the optional "thread_name" property from the json dump
generated by the stackwalker in the crashing stack header.

Example: <h2> Thread 3, Name: Timer</h2>

### CODE REVIEW

**Comment by adngdb** [comment]
Since this is quite difficult to test locally, I think we want to add a unit test to verify the thread name is displayed when existing. @CervantesYu do you think you'll be able to do that? If not, I can take care of it for you.

**Comment by CervantesYu** [comment]
@adngdb I'll need your help with the test. Thanks.

**Comment by adngdb** [comment]
I've opened https://github.com/CervantesYu/socorro/pull/1 to add a unit test for this.

**Comment by CervantesYu** [comment]
@adngdb The unit test is rebased and include in this PR. Would you perform the merge? Thanks.

**Comment by adngdb** [comment]
Thanks for contributing @CervantesYu !

**Pull request merged**
