### PR TITLE
No bug - Added a __init__.py to our scripts folder.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
``configman`` complains about this file missing locally when I try to run some of the scripts. 

@peterbe or @twobraids r?

### CODE REVIEW

**Comment by peterbe** [comment]
What's the complaint? Why are we importing things from that directory?

**Comment by twobraids** [comment]
I have the same questions...

**Comment by AdrianGaudebert** [comment]
Here's the error I get: 

```bash
(socorro-virtualenv)α ~/mozilla/workspace/socorro $ python scripts/setup_supersearch_app.py
Traceback (most recent call last):
  File "scripts/setup_supersearch_app.py", line 114, in <module>
    generic_app.main(SetupSuperSearchApp)
  File "/home/adrian/mozilla/workspace/socorro/socorro/app/socorro_app.py", line 493, in main
    values_source_list=values_source_list
  File "/home/adrian/mozilla/workspace/socorro/socorro/app/socorro_app.py", line 178, in run
    values_source_list=values_source_list
  File "/home/adrian/mozilla/workspace/socorro/socorro/app/socorro_app.py", line 244, in _do_run
    config_pathname=config_path
  File "/home/adrian/mozilla/workspace/socorro/socorro-virtualenv/local/lib/python2.7/site-packages/configman/config_manager.py", line 198, in __init__
    self.option_definitions
  File "/home/adrian/mozilla/workspace/socorro/socorro-virtualenv/local/lib/python2.7/site-packages/configman/def_sources/__init__.py", line 39, in setup_definitions
    target_setup_func(source, destination)
  File "/home/adrian/mozilla/workspace/socorro/socorro-virtualenv/local/lib/python2.7/site-packages/configman/def_sources/for_mappings.py", line 24, in setup_definitions
    val.set_value(val.default)
  File "/home/adrian/mozilla/workspace/socorro/socorro-virtualenv/local/lib/python2.7/site-packages/configman/option.py", line 117, in set_value
    new_value = self.from_string_converter(val)
  File "/home/adrian/mozilla/workspace/socorro/socorro/app/for_application_defaults.py", line 31, in str_to_application_class
    app_class = str_to_python_object(an_app_key)
  File "/home/adrian/mozilla/workspace/socorro/socorro-virtualenv/local/lib/python2.7/site-packages/configman/converters.py", line 158, in str_to_python_object
    raise CannotConvertError(str(x))
configman.config_exceptions.CannotConvertError: No module named scripts.setup_supersearch_app
```

**Comment by twobraids** [comment]
ok, that makes sense.  The setup_supersearch_app defers to the base ```SocorroApp``` class, which then turns around and imports the ```SetupSuperSearchApp``` class from the appropriate module.  In order for that import to succeed, the source file has to be part of a package.  

It's an awkward case whereas all the other Socorro applications are within the Socorro package hierarchy.  Resolving this would require reworking the ```SocorroApp``` invocation method: a low priority.  

Is there a place within the Socorro package hierarchy that this might be a better location?  The other apps (collector, processor, crontabber, ...) all have sub-packages directly within the ```socorro``` package.

**Comment by AdrianGaudebert** [comment]
Yes, this file should be in ``external/es/`` instead. I'll file a bug for that and close this PR. Thanks Lars!

**Pull request closed without merging**
