### PR TITLE
fixes bug 1189394 - Update travis to use Elasticsearch 1.4

### PR DESCRIPTION
**Pull request by peterbe**
Testing to find out what version of ES travis installs

### CODE REVIEW

**Comment by peterbe** [comment]
@AdrianGaudebert Now I it installs and runs ES 1.4.5 and it seems to get past that problem where groovy is needed. However, at the time of writing it fails on something in `test_supersearch.py`. Care to take a look?

Actually, I just restarted the tests seconds ago, in case it was a matter of "bad luck" but I think that was wishful thinking.

**Comment by AdrianGaudebert** [comment]
@peterbe I think this might be a specific test that's failing with ES1.4 for some weird reason. Maybe we can wait for https://github.com/mozilla/socorro/pull/2929 to be merged before doing this one? The other option could be to mark the failing test as running only on ES 0.90.

**Comment by peterbe** [comment]
I agree on doing that PR dependency. To #2929 !

**Comment by AdrianGaudebert** [comment]
Once #2929 is merged and this turns green, r+.

**Pull request merged**
