### PR TITLE
Fixes bug 1274213 - Removed remnants of the SkipList app.

### PR DESCRIPTION
**Pull request by adngdb**

### CODE REVIEW

**Comment by peterbe** [comment]
r+
I will merge if travis is happy.

**Comment by willkg** [comment]
Uh... I thought it was forbidden to remove migrations. I know it's a super bad idea to do in django-land.

**Comment by adngdb** [comment]
Remove migration? What do you mean?

**Comment by willkg** [comment]
Totally my bad--I misread the github notification email and thought this was removing an old alembic migration. Sorry!

**Pull request merged**
