### PR TITLE
Fixes bug 1123677 - Removed automatic emails cron job.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
@peterbe r?

### CODE REVIEW

**Comment by peterbe** [comment]
What about [suds](https://github.com/mozilla/socorro/blob/master/requirements.txt#L78) and stuff? I thought we needed that for exacttarget or whatnot.

**Comment by AdrianGaudebert** [comment]
Yes! Nice catch! We can remove ``suds`` and all ExactTarget related code.

**Comment by peterbe** [comment]
r+

**Comment by phrawzty** [comment]
dance

**Pull request merged**
