### PR TITLE
Fixes bug 1189395 - Added documentation about enabling Groovy for Ela…

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
…sticsearch.

@peterbe r?

### CODE REVIEW

**Comment by peterbe** [comment]
I can't get this to work. 
I start my local es like this: 
```
/opt/boxen/homebrew/bin/elasticsearch --config=/opt/boxen/homebrew/opt/elasticsearch/config/elasticsearch.yml
```
Homebrew generated that config file for me. (The version is 1.5.1)
The config file now looks like this: https://gist.github.com/peterbe/5f9bfa5ec4552520999c
Note my addition on line 26. 

When I run the test that depends on groovy
```
nosetests socorro/unittest/external/es/test_super_search_fields.py:IntegrationTestSuperSearchFields.test_update_field
```
I get this test error:
```
======================================================================
ERROR: test_update_field (socorro.unittest.external.es.test_super_search_fields.IntegrationTestSuperSearchFields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/dev/MOZILLA/SOCORRO/socorro/socorro/unittest/external/es/test_super_search_fields.py", line 143, in test_update_field
    storage_mapping={'type': 'long', 'analyzer': 'keyword'},
  File "/Users/peterbe/dev/MOZILLA/SOCORRO/socorro/socorro/external/es/super_search_fields.py", line 190, in update_field
    id=params['name'],
  File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 365, in update
    params=params, body=body)
  File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/elasticsearch/transport.py", line 284, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 54, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/Users/peterbe/virtualenvs/socorro/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[dynamic scripting for [groovy] disabled]; ')
```

And the output from the foreground elasticsearch is:
```
[2015-07-30 11:12:57,353][INFO ][node                     ] [Kylun] version[1.5.1], pid[33283], build[5e38401/2015-04-09T13:41:35Z]
[2015-07-30 11:12:57,354][INFO ][node                     ] [Kylun] initializing ...
[2015-07-30 11:12:57,358][INFO ][plugins                  ] [Kylun] loaded [], sites [head]
[2015-07-30 11:12:59,084][INFO ][node                     ] [Kylun] initialized
[2015-07-30 11:12:59,085][INFO ][node                     ] [Kylun] starting ...
[2015-07-30 11:12:59,176][INFO ][transport                ] [Kylun] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/127.0.0.1:9300]}
[2015-07-30 11:12:59,188][INFO ][discovery                ] [Kylun] elasticsearch_peterbe/cQdhZ-omSVaUxMZ1q-oEZw
[2015-07-30 11:13:02,961][INFO ][cluster.service          ] [Kylun] new_master [Kylun][cQdhZ-omSVaUxMZ1q-oEZw][Peters-MacBook-Pro.local][inet[/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
[2015-07-30 11:13:02,979][INFO ][http                     ] [Kylun] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
[2015-07-30 11:13:02,979][INFO ][node                     ] [Kylun] started
[2015-07-30 11:13:03,259][INFO ][gateway                  ] [Kylun] recovered [5] indices into cluster_state
[2015-07-30 11:13:19,030][INFO ][cluster.metadata         ] [Kylun] [socorro_integration_test] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2015-07-30 11:13:19,134][INFO ][cluster.metadata         ] [Kylun] [socorro_integration_test] update_mapping [supersearch_fields] (dynamic)
[2015-07-30 11:13:19,142][INFO ][cluster.metadata         ] [Kylun] [socorro_integration_test] update_mapping [supersearch_fields] (dynamic)
[2015-07-30 11:13:19,285][INFO ][cluster.metadata         ] [Kylun] [socorro_integration_test_reports] creating index, cause [api], templates [], shards [5]/[1], mappings [crash_reports]
[2015-07-30 11:13:19,345][INFO ][cluster.metadata         ] [Kylun] [socorro_mapping_test] creating index, cause [api], templates [], shards [5]/[1], mappings [crash_reports]
[2015-07-30 11:13:19,393][INFO ][cluster.metadata         ] [Kylun] [socorro_mapping_test] deleting index
[2015-07-30 11:13:19,427][INFO ][cluster.metadata         ] [Kylun] [socorro_integration_test] update_mapping [supersearch_fields] (dynamic)
[2015-07-30 11:13:19,467][INFO ][cluster.metadata         ] [Kylun] [socorro_mapping_test] creating index, cause [api], templates [], shards [5]/[1], mappings [crash_reports]
[2015-07-30 11:13:19,505][INFO ][cluster.metadata         ] [Kylun] [socorro_mapping_test] deleting index
[2015-07-30 11:13:19,543][INFO ][cluster.metadata         ] [Kylun] [socorro_integration_test] deleting index
[2015-07-30 11:13:19,571][INFO ][cluster.metadata         ] [Kylun] [socorro_integration_test_reports] deleting index
```

**Comment by peterbe** [comment]
If I run the test without logging disabled I get this:
https://gist.github.com/peterbe/5de20335965971070753

**Comment by AdrianGaudebert** [comment]
OK my bad. After talking with @phrawzty I realized I was giving a config option that is only supported in ES 1.5+, and you are (rightfully since that's what we use on prod) using 1.4. The actual setting is ``script.disable_dynamic: false``. I'm updating this.

**Comment by peterbe** [comment]
r+ 

I did that to my yml file for my 1.5 and now I can run that test that has breaking before.

**Pull request merged**
