### PR TITLE
Fixes bug 1308892 - Made Simple Search inputs accept custom values.

### PR DESCRIPTION
**Pull request by adngdb**

### CODE REVIEW

**Comment by peterbe** [comment]
I'm not done reviewing. But something strange is going on when I type in a bunch of versions. It simply isn't included in the filtering. 
See:
screen shot 2016-10-11 at 9 46 02 pm

**Comment by adngdb** [comment]
@peterbe problem solved!

**Comment by peterbe** [comment]
If I type something into the Versions field, and let the autocomplete work for me, then what I started typing is still there. 

Steps to reproduce:
1) Go to http://socorro.dev/search/?product=Firefox&_dont_run=1
2) Type in "52", the first dropdown choice/suggestion is "52.0a1", just hit Enter
3) This happens:
screen shot 2016-10-14 at 11 42 47 am

**Comment by peterbe** [comment]
Something is really broken. I've refreshed and checked and it's running the latest code. 

1) I type in two versions. E.g "52.0a1" and "49.0.1"
2) Hit Search
3) On "More options..." click to expand. 

Note the `undefined=52.0a1&...` in the URL
screen shot 2016-10-14 at 11 47 44 am

But note, if I facet on version, it does actually work:

screen shot 2016-10-14 at 11 48 28 am

**Comment by adngdb** [comment]
@peterbe all should work fine now. Thanks for spotting these problems, and sorry I haven't done that myself!

**Comment by peterbe** [comment]
Works awesomely 🍔

**Pull request merged**
