### PR TITLE
bug 1280097 - Remove support for scraping b2g nightlies

### PR DESCRIPTION
**Pull request by nthomas-mozilla**

### CODE REVIEW

**Comment by nthomas-mozilla** [comment]
The motivation is - B2G isn't producing any nightlies any more, and other products don't create manifest files, so this is dead code.

**Comment by peterbe** [comment]
We actually removed it from config some time ago: https://github.com/mozilla/socorro/pull/3372/files
What you've taken care of is the last sentence on: https://bugzilla.mozilla.org/show_bug.cgi?id=1280097#c4

The code is good but can you please rebase this and attach the bug number https://bugzilla.mozilla.org/show_bug.cgi?id=1280097 to the commit message? And make it 
```
fixes bug 1280097 - Remove scraping b2g nightlies code
```

**Comment by peterbe** [comment]
With the new GitHub PR I can rebase but I can't change the commit message.

**Comment by nthomas-mozilla** [comment]
Rebased and commit message fixed up.

**Comment by peterbe** [comment]
🏅 Thank you!

**Pull request merged**
