### PR TITLE
Fixes bug 1177605 - Added sub aggregations for signature facets.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**

### CODE REVIEW

**Comment by AdrianGaudebert** [comment]
TODO: Add a parameter to overwrite the number of results per facet.

**Comment by AdrianGaudebert** [comment]
@peterbe r?

**Comment by peterbe** [comment]
Why the TODO comment? Is this now done on [line 216](https://github.com/mozilla/socorro/pull/2869/files#diff-9a5901fadfb434f17d8519068f1fb973R216)?

**Comment by peterbe** [comment]
r+ 

But I would recommend that you squash your commits. Having a breaking commit means you can't do git bisect to hunt down where tests fail.

**Comment by peterbe** [comment]
Closed?!

**Comment by AdrianGaudebert** [comment]
Oops, the commit didn't make it to this PR. It's in master: https://github.com/mozilla/socorro/commit/1c06eab09d48a53b5ecc38a539c87dfd04deeeac

**Pull request closed without merging**
