### PR TITLE
Bug 1275482 - Added a processed crash JSON schema file.

### PR DESCRIPTION
**Pull request by adngdb**
@lonnen r?

### CODE REVIEW

**Comment by lonnen** [comment]
This is awesome! I would add a README in the folder describing how the schemas folder will be used to differentiate it from the database schema.

**Comment by lonnen** [comment]
Did you consider running the validation as part of the test suite?

**Comment by lonnen** [comment]
Other than that question for consideration, r+

**Comment by nnethercote** [comment]
Any reason this hasn't landed yet? I ask because I am writing some docs on how to read individual crash reports (https://developer.mozilla.org/en-US/docs/Understanding_crash_reports) and I'd like to link to this file in order to show where the field descriptions come from. Thanks.

**Comment by adngdb** [comment]
@lonnen the validation script relies on network / prod, I made it more as a tool to verify a mapping works during development than as a unit test. However, if going forward we begin to rely on those files in our code base, I think we will want to test them, using a different approach.

**Comment by nnethercote** [comment]
Is the JSON schema hooked up for actual use on crash-stats? Apologies for asking, it's still a little unclear to me how the field tool-tips in crash-stats are generated. (And I noticed that the tooltips for fields in the "Metadata" tab lack descriptions even when the same fields in the "Details" tab have descriptions, and I'm wondering if this change will fix this?)

**Comment by adngdb** [comment]
No, at the moment it is just a fairly representation of what a processed crash looks like, but it is not being used anywhere. I suspect we will want to adapt it if we do use it. I do not think we will use it to validate what the processors generate. The initial need was to have a reference for security to verify what we would send over to Telemetry, and to have a schema that they can use on their side to validate what we send them. It is still unclear how exactly this is going to be used in the future.

Regarding the Metadata tab missing descriptions, that is because all fields in that tab come from the raw crash, and none of those fields have been documented. Only their equivalents in the processed crash have been, but even if they are the same data, we need to document both in our Super Search Fields tool. This work is unrelated, it only cares about the processed crash.

**Pull request merged**
