### PR TITLE
Fixes bug 1263781 - Added nsTHashtable-related signatures to prefix list.

### PR DESCRIPTION
**Pull request by adngdb**

### CODE REVIEW

**Comment by peterbe** [comment]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1263781#c2 njn listed 10 entries. You only have 9 additions. A quick scripted analysis says you're missing `nsRefPtrHashtable<.*>::.*`.

**Comment by nnethercote** [comment]
r=me with the nsRefPtrHashtable entry added. Thank you.

**Comment by adngdb** [comment]
Ah, yeah, forgot to mention it but ``nsRefPtrHashtable<.*>::.*`` was already in there under this form: ``nsRefPtr.*``. So in practice everything should be covered.

**Comment by peterbe** [comment]
rebase needed. r+

**Pull request merged**
