### PR TITLE
Fixes bug 1215153 - Added links to Profile page, removed tokens.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
@peterbe r?

### CODE REVIEW

**Comment by peterbe** [comment]
screenshot 2015-11-03 07 53 29
Alignment is wrong. The top bar (with the links) is larger than the two boxed below.

**Comment by peterbe** [comment]
The way it says my email address in the upper right-hand corner (sort of) is odd. It's sitting there. It's not clickable or anything.

**Comment by peterbe** [comment]
I think you should NOT put the email address alone up there and instead change the link from "Sign out" to "Sign out pbengtsson@mozilla.com"

**Comment by AdrianGaudebert** [comment]
@peterbe comments addressed!

**Comment by peterbe** [comment]
How about this?
screenshot 2015-11-06 08 35 48

It's bad enough that the `<h2>Your Profile</h2>` is floating in the empty sea and not inside a box. 

Either way, if you prefer having the sign out like you have it, then r+
Otherwise, consider my counter PR.

**Comment by peterbe** [comment]
Either accept https://github.com/AdrianGaudebert/socorro/pull/4 or ignore it and I won't be offended at all.

**Pull request merged**
