### PR TITLE
Fixes bug 1127783 - By default, load Elasticsearch mapping data from dat...

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
...abase instead of a file.

@phrawzty r?

### CODE REVIEW

**Comment by AdrianGaudebert** [comment]
Hah, only automatic-emails tests are failing. Let's wait until #2610 is merged and the problem will be solved... :-)

**Comment by phrawzty** [comment]
Why do this :question:

**Comment by AdrianGaudebert** [comment]
This configuration option is used to determine if the Elasticsearch mapping for new indices is loaded from a file (in our repository) or from the database (using the Super Search Fields list). It was set to ``True`` by default because that's how it has been working historically. Then we turned it to ``False`` in staging and production. Now that we know loading that data from our database works well, we should make it ``False`` by default, so our external users benefit it.

**Comment by phrawzty** [comment]
Thanks for the clarification!

`r+`

**Pull request merged**
