### PR TITLE
Update tar_crashes.py and cron_libraries.sh based on whats working on prod

### PR DESCRIPTION
**Pull request by jdotpz**
Adds tar_crashes.py and cron_libraries.sh

### CODE REVIEW

**Comment by rhelmer** [comment]
r+

**Comment by jdotpz** [comment]
I updated paths in the cron_libraries.sh script.

**Comment by twobraids** [comment]
so what about the other changed scripts from that PR over in socorro-infra?  ```cron_daily_reports.sh``` and ```cron_missing_symbols.sh``` both have extensive modifications, too.  

And I'd rather see the ```tar_crashes.py``` in the ```.../scripts/...``` directory since it is not actually a cron job itself.

**Comment by peterbe** [comment]
other things will cover this same issue

**Pull request closed without merging**
