### PR TITLE
Bug 1252887 - Update forced versions for correlations for Firefox cycle starting 2016-03-07

### PR DESCRIPTION
**Pull request by KaiRo-at**
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod early next week (2016-03-07 or closely after).

Note that once again we need to update the crash-analysis node with that code (and make sure this version of the script is actually being run) to actually make it live.

### CODE REVIEW

**Comment by peterbe** [comment]
Out of curiosity, why don't we do 47 on correlations? Too few crashes?

**Comment by peterbe** [comment]
r+ 
There's no point waiting for Travis on this.

**Comment by KaiRo-at** [comment]
> Out of curiosity, why don't we do 47 on correlations? Too few crashes?

Not sure what you mean 47.0a2 is in there, and that's where the 47 train will live for the next 6 weeks.

**Comment by peterbe** [comment]
Oops. I searched poorly.

**Pull request merged**
