### PR TITLE
fixes bug 1156394 - Use dj-database-url to unpackage settings.DATABASES

### PR DESCRIPTION
**Pull request by peterbe**
r? @rhelmer

### CODE REVIEW

**Comment by peterbe** [comment]
Oh. I think I missed the ci part.

**Comment by peterbe** [comment]
Actually, this is tricky. 
You actually get a warning in the [travis tests](https://api.travis-ci.org/jobs/59293735/log.txt?deansi=true) because the travis tests rely on the defaults. (e.g. `django.db.backends.sqlite3` and `sqlite.crashstats.db`)

So, we actually only want to bother with the deprecation warning IF the `DATABASE_URL` is NOT set and some of the `DATABASE_*` settings are.  I'll need to modify the code.

**Comment by peterbe** [comment]
Right. Addressed in the last commit.

**Comment by peterbe** [comment]
@rhelmer ping

**Comment by rhelmer** [comment]
So nice. Now we just need to switch everything over to it :)

**Comment by rhelmer** [comment]
r+

**Pull request merged**
