### PR TITLE
Bug 1305129 upgrade pyopenssl pyasn1 and ndg httpsclient

### PR DESCRIPTION
**Pull request by peterbe**
This makes https://github.com/mozilla/socorro/pull/3465/files obsolete because I couldn't upgrade pyOpenSSL without also upgrading crytography.

### CODE REVIEW

**Comment by peterbe** [comment]
By the way, after installing this update in my local virtualenv I tested that the google analytics also worked. I also testing google sign in. I did not test ftpscraper but it's extremely unlikely to be any different from the requests.post that the google analytics ping does.

**Comment by adngdb** [comment]
``pyOpenSSL`` is already being updated in https://github.com/mozilla/socorro/pull/3465/files.

**Comment by adngdb** [comment]
Actually, why don't you update ``cryptography`` here as well, and then we can get rid of #3465 ?

**Comment by peterbe** [comment]
> Actually, why don't you update cryptography here as well, and then we can get rid of #3465 ? 

It does. This PR is what #3465 is but more.

**Pull request merged**
