### PR TITLE
No bug - Added a config file for eslint.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
@peterbe So this is mostly enforcing the default rules. Many failures I see are caused by undefined global variables like ``$``, but there are other interesting things, like missing semicolons, wrong indentation, etc. Once we agree on a ruleset I'll try to fix at least a few files, and maybe add that to our build process (though I doubt I'll do it on the ``crashstats`` app's JS files, because they are quite a mess).

### CODE REVIEW

**Comment by AdrianGaudebert** [comment]
Btw the list of default rules is here: http://eslint.org/docs/rules/

**Comment by peterbe** [comment]
What does this mean??
```
(socorro):~/socorro/webapp-django (bug-1198531-drop-laglog-table %)$ ff '\.js$'  | grep -v lib | grep -v 'min\.js' | grep -v jquery | grep -v 'pack\.js' | xargs eslint

/opt/boxen/nodenv/versions/v0.10.35/lib/node_modules/eslint/lib/config.js:120
                throw e;
                      ^
Error: Cannot find module 'eslint-config-eslint:recommended'
Referenced from: /Users/peterbe/dev/MOZILLA/SOCORRO/socorro/webapp-django/.eslintrc
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at loadConfig (/opt/boxen/nodenv/versions/v0.10.35/lib/node_modules/eslint/lib/config.js:91:34)
    at loadConfig (/opt/boxen/nodenv/versions/v0.10.35/lib/node_modules/eslint/lib/config.js:114:44)
    at getLocalConfig (/opt/boxen/nodenv/versions/v0.10.35/lib/node_modules/eslint/lib/config.js:215:23)
    at Config.getConfig (/opt/boxen/nodenv/versions/v0.10.35/lib/node_modules/eslint/lib/config.js:357:22)
    at processFile (/opt/boxen/nodenv/versions/v0.10.35/lib/node_modules/eslint/lib/cli-engine.js:178:27)
    at /opt/boxen/nodenv/versions/v0.10.35/lib/node_modules/eslint/lib/cli-engine.js:332:26
```

**Comment by peterbe** [comment]
I tried upgrading my eslint but now it's hosed.
```
(socorro):~/socorro/webapp-django (bug-1198531-drop-laglog-table %)$ eslint --version

module.js:340
    throw err;
          ^
Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/boxen/nodenv/versions/v0.10.35/lib/node_modules/eslint/node_modules/concat-stream/index.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by peterbe** [comment]
Ok. Upgrading my npm and re-installing eslint made that `readable-stream` problem go away. 

However, even with the latest eslint I can't get it to work with that last line (`extends: 'eslint:recommended'`)

**Comment by AdrianGaudebert** [comment]
Well that's very weird because it's part of the default file generated by ``eslint --init``. What versions of npm and eslint do you run? I have: 

```bash
α ~ $ npm --version
2.12.0
α ~ $ eslint --version
v1.6.0
```

**Comment by peterbe** [comment]
Aha! I seems when I ran `npm install -g eslint` it didn't upgrade
```
(socorro):~/dev/MOZILLA/SOCORRO/socorro (bug-1198531-drop-laglog-table %)$ npm --version
3.3.5
(socorro):~/dev/MOZILLA/SOCORRO/socorro (bug-1198531-drop-laglog-table %)$ eslint --version
v0.21.2
```

**Comment by peterbe** [comment]
Now it's working. 

I have something I'd like to add to this file though. We have so many .js files that depend on `$` being available. I think there's a way to say that that's always a global so you don't have to put `/* Globals: $:true */` (or whatever it is) in every file.

**Comment by rhelmer** [comment]
@peterbe you can do this in your `.eslintrc`:

```
        globals: {
            'jQuery':false,
            '$':true
        },
```

**Comment by AdrianGaudebert** [comment]
It's even easier: I just had to add ``jquery`` in the list of environments. :)

**Comment by peterbe** [comment]
It's a great start! Now we just need to start using it :)

**Pull request merged**
