### PR TITLE
Fixes bug 1273538 - Correctly encode white spaces in URLs.

### PR DESCRIPTION
**Pull request by adngdb**
``$.param`` uses the ``+`` sign to encode white spaces. So I added a new library to Socorro, called ``Qs``, to deal with query string creation.

### CODE REVIEW

**Comment by peterbe** [comment]
We chatted about it briefly on IRC, and the question was; why is this Qs thing better than `$.param`?
I saw that you're doing the string replace of `+` for `%20` anyway, which was the beef we had with `$.param` and I believe that was entirely fixed with that one string replace.

**Comment by adngdb** [comment]
There are two different things happening here. The first one is that I replaced ``$.param`` with ``Qs.stringify``, because the latter uses ``%20`` as the encoding character for white spaces (as opposed to ``+``, which causes bugs with the rest of our code). The second thing is that Python's ``urllib.urlencode`` also uses ``+`` to encode white spaces, so I am replacing all ``+`` characters with the "correct" ``%20`` string. This way we are consistent everywhere (I hope) in our encoding, and we do not use the ``+`` character as an encoding character.

**Comment by peterbe** [comment]
I think I get what this PR does. You consolidate so it's `%2B` instead of `+` BOTH in python AND in all javascript. In other words, I understand the code in the PR. But...

I don't want to stand in your way for progress but I'm also interested in learning. So...

What's the problem we're trying to fix? Like, what is broken/breaking?
One possible answer is that maybe [this pr](https://github.com/mozilla/socorro/pull/3335) wouldn't have been necessary if all `+` gone.

**Comment by peterbe** [comment]
By the way, instead of adding a big new js library you could just define a global function like
```javascript
window.urlencode = function(params) {
    return $.param(params, {indices: false}).replace(/\+/g, '%2B');
};
```

**Comment by adngdb** [comment]
#3335 was indeed the root of this problem. It fixed an issue when users were writing things like ``WebGL+``, but it broke cases when they used phrases like ``foo bar``. Those are currently turned into ``foo+bar``, and that's then interpreted as such by Super Search because we removed the replacement of ``+`` with white spaces. If you want to see this for yourself, go to Super Search on prod and search for ``cpu info`` ``starts with`` ``AuthenticAMD family 20``. You should see quite a few crash reports. Now click any of the signatures to go to Signature report, and it will have no results, because the query became ``cpu info`` ``starts with`` ``AuthenticAMD+family+20``.

**Comment by peterbe** [comment]
Ah! So this solves something I broke. Hehe. Thanks for the clear example. 

r+

But I still think you should consider taking a look at [my `window.urlencode`](https://github.com/mozilla/socorro/pull/3348#issuecomment-220027057) function first.

**Comment by adngdb** [comment]
I understand the value of not adding too much JS to our pages, but I also like using focused libraries instead of big, do-it-all ones like jQuery. ``Qs`` takes care of query strings and does it well for what I have seen. 

Also, I find it a lot cleaner and less confusing than your hack. It's easier to find documentation about how this library works than to have to search our code to find out where our hack is.

**Pull request merged**
