### PR TITLE
fixes bug 1240107 - Expose a /healthcheck endpoint that ELB can hit

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
@adngdb @jdotpz 
So, note the "XXX" comment in there. I don't know how to make a really basic ES query from the webapp. It would be good to have that, so that when we point Pingdom on this we include testing that the ES server is at least responding. We actually have `settings.SOCORRO_IMPLEMENTATIONS_CONFIG['elasticsearch']['elasticsearch_urls']` available to us and we could use that. 

@adngdb Can you help out with that?

@jdotpz Do you mind waiting till we've had some help from Adrian?

**Comment by jdotpz** [comment]
NP, take all the time you need.  I'll just have to get busy PTO'ing :)

**Comment by peterbe** [comment]
@adngdb I've removed the fs disk check after talking to @jdotpz on irc. 
Also I changed the ES check to be mocked. 
r?

**Comment by adngdb** [comment]
r+

**Pull request merged**
