### PR TITLE
fixes bug 1252623 - Graphics devices pure implementation

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by adngdb** [comment]
I'm having an error when trying to add a new graphic device in the admin panel: 

```
Request Method: POST
Request URL: http://localhost:8000/admin/graphics-devices/

Traceback:
File "/home/adrian/mozilla/workspace/socorro/socorro-virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/adrian/mozilla/workspace/socorro/webapp-django/crashstats/manage/views.py" in inner
  99.         return view_func(request, *args, **kwargs)
File "/home/adrian/mozilla/workspace/socorro/webapp-django/crashstats/manage/views.py" in graphics_devices
  476.             result = api.post(json.dumps(payload))
File "/home/adrian/mozilla/workspace/socorro/webapp-django/crashstats/crashstats/models.py" in post
  1708.         return self.implementation().post(payload)
File "/home/adrian/mozilla/workspace/socorro/socorro/external/postgresql/base.py" in __init__
  46.             self.database = self.context.database_class(

Exception Type: AttributeError at /admin/graphics-devices/
Exception Value: 'NoneType' object has no attribute 'database_class'
```

**Comment by peterbe** [comment]
I'm glad you tested. That stuff is too mocked out. Anyway, I fixed it and have now successfully updated the graphics devices.

**Comment by peterbe** [comment]
Back in the day when the middleware_app didn't do much before protecting the implemenations we had to assume the implementation got a JSON string coming in. Because that's what the middleware did. Now we can work with pure python lists and dicts.

**Comment by adngdb** [comment]
r+

**Pull request merged**
