### PR TITLE
fixes bug 1257728 - Links from crash report stack to hg.mozilla.org s…

### PR DESCRIPTION
**Pull request by peterbe**
…hould use HTTPS

### CODE REVIEW

**Comment by willkg** [comment]
This failed with:

```
***** BEGIN correlation diff *****
diff -w ./correlations/20151130/20151130_Firefox_42.0-interesting-modules.json ./testcrash/correlations-integration-correct-output/20151130_Firefox_42.0-interesting-modules.json
2750,2751c2750,2751
<                             "in_os_count": 2, 
<                             "in_os_ratio": 50, 
---
>                             "in_os_count": 3, 
>                             "in_os_ratio": 75, 
3840,3841c3840,3841
<                             "in_os_count": 2, 
<                             "in_os_ratio": 50, 
---
>                             "in_os_count": 3, 
>                             "in_os_ratio": 75, 
4895,4896c4895,4896
<                             "in_os_count": 2, 
<                             "in_os_ratio": 50, 
---
>                             "in_os_count": 3, 
>                             "in_os_ratio": 75, 
***** END correlation diff *****
ERROR: ERROR: correlations produced unexpected output
INFO: Purging rabbitmq queue socoro.integrationtest.normal
INFO: Purging rabbitmq queue socoro.integrationtest.priority
INFO: Purging rabbitmq queue socoro.integrationtest.reprocessing
INFO: cleaning up crash storage directories
```

My meager neophyte understanding of the great expansive universe that is Socorro doesn't see why that would be affected by the protocol used for hg.mozilla.org, so I told Travis to try again.

**Comment by peterbe** [comment]
Yeah, that's a repeating nuisance in our test suite. It was a test added in rush by Lars in late 2015 and nobody has had time to understand it yet. It's related to thread-un-safety.

**Comment by willkg** [comment]
I did a skim of socorro bugs, but didn't see one for that. Is there one? If not, I'll write one up.

**Comment by peterbe** [comment]
There is no bug I don't think.

On Friday, March 18, 2016, Will Kahn-Greene <notifications@github.com>
wrote:

> I did a skim of socorro bugs, but didn't see one for that. Is there one?
> If not, I'll write one up.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/socorro/pull/3247#issuecomment-198350644>
>


-- 
Peter Bengtsson
Mozilla Tools & Services

**Comment by lonnen** [comment]
filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1258267

I'd like to get a full build log in there at some point. When we reran this I think we lost the old one.

**Pull request merged**
