### PR TITLE
Bug 1297452: tell travis to use 2.7.11

### PR DESCRIPTION
**Pull request by willkg**

### CODE REVIEW

**Comment by willkg** [comment]
Travis kept failing with "exit code 8" and no indication of what the actual problem was. Then on a lark, I deleted the cache for the PR in Travis and once I did that, it passed. Maybe there's a causal relationship? Maybe the @lonnen is manipulating the strings of the universe and toying with me? Will I ever know for sure?

Anyhow, it's ready for landing.

To review:

1. Check the diff--sorry for the absurd length.
2. Skim the top of the Travis log where it will tell you in no uncertain terms that it used Python 2.7.11.

@peterbe Can you review this one? It should be a quickie.

**Comment by jdotpz** [comment]
LGTM but I think we may want to merge, as we reverted.

**Comment by willkg** [comment]
I'm going to land this. We'll move to Python 2.7.11 eventually, and we're definitely not using 2.7.9, so seems like it's a good move.

**Comment by jdotpz** [comment]
r+

**Pull request merged**
