### PR TITLE
fixes bug 1295154 - Bad regex on symbol upload expressions

### PR DESCRIPTION
**Pull request by peterbe**
Ted, if you don't have time to review, please throw this over to @adngdb

### CODE REVIEW

**Comment by peterbe** [comment]
@luser Normally, we let the reviewer merge, as opposed to leaving a "r+" comment. But in this case, let's not. Reason is that @jdotpz is debugging things on our stage servers and a merge to master would trigger a new build and that might make things hard for him.

**Comment by peterbe** [comment]
@willkg can you review this mayhaps?

**Comment by willkg** [comment]
I don't think I can review this. I vaguely understand what's going on, but don't understand the big picture and I've got a ton of stuff I need to get done this week. Sorry. :(

**Comment by luser** [comment]
This looks good to me. (Not merging because of deployment status.)

**Pull request merged**
