### PR TITLE
fixes bug 1166838 - new peep hashes for github.com .zip files

### PR DESCRIPTION
**Pull request by peterbe**
@rhelmer r?

PS. I deleted all [cache repositories](https://travis-ci.org/mozilla/socorro/caches) on Travis just prior to starting this PR.

### CODE REVIEW

**Comment by rhelmer** [comment]
r+ if travis is happy. I'll take care of Jenkins caches (if it needs it)

**Comment by peterbe** [comment]
What the heck! Are we [not using peep in travis](https://github.com/mozilla/socorro/blob/master/.travis.yml#L24)?
That means that travis won't check any of the peep hashes.

**Comment by rhelmer** [comment]
> That means that travis won't check any of the peep hashes. 

It looks like we're running `pip` and then later `peep`.

**Comment by rhelmer** [comment]
Not waiting for Travis, it's crawling right now. Jenkins will test this.

**Pull request merged**
