### PR TITLE
Pass in 'xterm' to ansiColor()

### PR DESCRIPTION
**Pull request by stephendonner**
(Sadly, needed due to a change in Pipeline Model/plugins.)

@davehunt @willkg @m8ttyB ?

### CODE REVIEW

**Comment by stephendonner** [comment]
The following exception showed up when we upgraded our staging Jenkins with the latest Pipeline Model Definition plugin (and associated ones):

```
http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/socorro.adhoc/32/console

WorkflowScript: 13: "ansiColor" should have 1 arguments but has 0 arguments instead. @ line 13, column 5.
       ansiColor()
       ^
```

**Comment by stephendonner** [comment]
Specifically, see https://issues.jenkins-ci.org/browse/JENKINS-42772

**Comment by willkg** [comment]
I don't have any opinions on this. I defer to @davehunt and @m8ttyB. I can merge it if someone else r+ it.

**Comment by davehunt** [comment]
r+ please merge when convenient @willkg

**Pull request merged**
