### PR TITLE
(no bug) - more explicit instructions on how to get consul going

### PR DESCRIPTION
**Pull request by rhelmer**
r? anybody

### CODE REVIEW

**Comment by phrawzty** [comment]
A relative path for `-data-dir` - that seems odd, no?

**Comment by rhelmer** [comment]
@phrawzty true... the docs use `/tmp` but that seems rude. What do you think would be better?

**Comment by phrawzty** [comment]
We use `/var/lib/consul` for reasonable reasons, so that's a possibility.  Honestly, imho anything would be better than a relative directory - we could even just put `-data-dir /dir/of/your/choosing/` fwiw. :cake:

**Comment by rhelmer** [comment]
@phrawzty let's use `/var/lib/consul` and throw a `sudo` in there, lack of write permission was the thing I was worried about.

**Comment by phrawzty** [comment]
This is high-quality bikeshed material, so let's just `r+` and move along. :wink:

**Pull request merged**
