### PR TITLE
webqapassing tool

### PR DESCRIPTION
**Pull request by peterbe**
cc @lonnen @jdotpz @m8ttyB

I wrote this. Primarily for myself, as a tool to be more careful when I push out a release tag, that WebQA tests are healthy. In particular, stage. I.e. stage shouldn't have become broke from recent changes if you're pushing to prod. 

This PR is basically to put that script into the repo or not.

### CODE REVIEW

**Comment by adngdb** [comment]
I do not mind having such tools in the code base.

**Comment by peterbe** [comment]
screen shot 2016-02-24 at 2 11 25 pm

**Comment by peterbe** [comment]
Can I just land this?

**Comment by adngdb** [comment]
I'm fine with it. What does @lonnen think?

**Pull request merged**
