### PR TITLE
fixes bug 1306734 - Upgrade to django-session-csrf 0.7.0

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by adngdb** [comment]
I'm actually considering this as "Major" because it updates a dependency, and that can have unexpected side-effects.

**Comment by peterbe** [comment]
I actually know what the difference is between 0.6 and 0.7.0, since I was the one who reviewed and merged that one :)
The change just makes it possible to run django-session-csrf in Django 1.10. It's still perfectly compatible with our Django 1.8.

**Comment by adngdb** [comment]
Sadly, this needs rebasing now. :(

**Comment by peterbe** [comment]
Rebased now.

**Pull request merged**
