### PR TITLE
Bug 1241343 - Update forced versions for correlations for Firefox cycle starting 2016-01-25

### PR DESCRIPTION
**Pull request by KaiRo-at**
This adds current aurora and nightly versions as well as all planned beta versions for this cycle, and should land on prod early next week (2016-01-25 or closely after).

Note that once again we need to update the crash-analysis node with that code (and make sure this version of the script is actually being run) to actually make it live.

### CODE REVIEW

**Comment by peterbe** [comment]
If I merge this now, nothing happens. Right?
The real work is in "updating" that `/data/bin/cron_libraries.sh` file on prod crash-analysis. 
The really important thing is that we need to apply this ON the 25th of Jan, so it takes effect on the wee hours of the 26th.

**Comment by peterbe** [comment]
How about we merge this now and book a calendar appointment between you, @jdotpz and myself to go in and do the upgrade however that's best done?

**Comment by jdotpz** [comment]
If we go ahead and move where the cron job is pointing to instead, we can have one person simply run a 'sudo yum install socorro' to update to the current socorro code with the correct versions.

**Comment by KaiRo-at** [comment]
Yes, we can merge this right away only only deploy ideally on Monday.

And also yes, I think we should point the cron job to the socorro version of this script and do this simple deploy then.

**Comment by peterbe** [comment]
r+

**Comment by peterbe** [comment]
@jdotpz, @KaiRo-at and I will ping you on Monday to do that rearrange and yum thing.

**Pull request merged**
