### PR TITLE
bug 1258267 - fewer threads in correlations integration test

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by peterbe** [comment]
Passed once.

**Comment by peterbe** [comment]
Starting a second time. Sorry for the noise.

**Comment by peterbe** [comment]
Passed twice.

**Comment by peterbe** [comment]
Starting third time.

**Comment by peterbe** [comment]
Passed a third time.

**Comment by peterbe** [comment]
Trying a fourth time.

**Comment by peterbe** [comment]
Passed a fourth time.

**Comment by peterbe** [comment]
Test a fifth time.

**Comment by peterbe** [comment]
cc @twobraids @lonnen 

Now it's worked 5 times in a row without that common strange json diff error.

**Comment by willkg** [comment]
Is it important to test it in a threading situation in the integration tests? This is how we have prod set up.

**Comment by adngdb** [comment]
r+ but I think Will's question is valid.

**Comment by peterbe** [comment]
Testing with 2 threads. It should do both multiple threads (greater than 1) AND not too many to cause race conditions.

**Comment by peterbe** [comment]
Worked with 2 threads.

**Comment by peterbe** [comment]
Trying again.

**Comment by peterbe** [comment]
Trying again second time with 2 threads.

**Comment by peterbe** [comment]
Let's go!

**Pull request merged**
