### PR TITLE
Fixes bug 1289704 - Use ruby 2 in travis build process.

### PR DESCRIPTION
**Pull request by adngdb**
Trying to see if that fixes the issue.

### CODE REVIEW

**Comment by adngdb** [comment]
\o/

Thanks @luser! @peterbe r?

**Comment by adngdb** [comment]
cc @jdotpz too, in case there are consequences to using rvm 2 that I do not know of.

**Comment by peterbe** [comment]
r+

**Comment by peterbe** [comment]
But is it travis that we use to build the build artifact?? I thought it was Jenkins that does that.

**Pull request merged**
