### PR TITLE
No Bug - corrected wrong base class for copy raw & processed app

### PR DESCRIPTION
**Pull request by twobraids**
correct error in selection of a base class for an ad hoc app.

### CODE REVIEW

**Comment by rhelmer** [comment]
@twobraids tested this in AWS, and seeing:

```
2015-06-10 17:46:34,631 DEBUG - raw_and_processed_crash_copier -  - MainThread - waiting to join queuingThread
2015-06-10 17:46:34,663 DEBUG - raw_and_processed_crash_copier -  - QueuingThread - yielding ('88518099-e320-42e8-8357-71ac32150101',)
2015-06-10 17:46:34,663 DEBUG - raw_and_processed_crash_copier -  - QueuingThread - yielding None
2015-06-10 17:46:34,663 INFO - raw_and_processed_crash_copier -  - QueuingThread - there is nothing to do.  Sleeping for 7 seconds
2015-06-10 17:46:35,019 ERROR - raw_and_processed_crash_copier -  - Thread-1 - Error in processing a job
Traceback (most recent call last):
  File "/data/socorro/socorro-virtualenv/lib/python2.7/site-packages/socorro-master-py2.7.egg/socorro/lib/threaded_task_manager.py", line 342, in run
    function(*args, **kwargs)  # execute the task
  File "/data/socorro/socorro-virtualenv/lib/python2.7/site-packages/socorro-master-py2.7.egg/socorro/collector/crashmover_app.py", line 172, in transform
    crash_id
  File "/data/socorro/socorro-virtualenv/lib/python2.7/site-packages/socorro-master-py2.7.egg/socorro/external/es/crashstorage.py", line 183, in save_raw_and_processed
    copied_processed_crash = deepcopy(processed_crash)
  File "/usr/lib64/python2.7/copy.py", line 172, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
KeyError: '__deepcopy__'
```

**Comment by twobraids** [comment]
I removed the deep copy from the ES crashstorage class.  since this isn't a general use crashstorage class, I just added a warning that this crashstore class is destructive to the processed_crash.  If  used with a PolyCrashstore, the redacted processed crash may be stored in the other crash stores.

**Comment by rhelmer** [comment]
As discussed in IRC - latest change gets us further, but ES is now unhappy about the timestamp format:

```
RequestError: TransportError(400, u'RemoteTransportException[[i-5feaf396][inet[/172.31.9.113:9300]][indices:data/write/index]]; nested: MapperParsingException[failed to parse [processed_crash.client_crash_date]]; nested: MapperParsingException[failed to parse date field [2015-01-01 23:59:22.000000], tried both date format [yyyy-MM-dd\'T\'HH:mm:ssZZ||yyyy-MM-dd\'T\'HH:mm:ss.SSSSSSZZ], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "2015-01-01 23:59:22.000000" is malformed at " 23:59:22.000000"]; ')
```

**Comment by rhelmer** [comment]
r+

**Pull request merged**
