### PR TITLE
fixes bug 1186454 - Document structure of symbol files to be uploaded

### PR DESCRIPTION
**Pull request by peterbe**
@luser if you can make a PR towards my fork, we should have enough to at least have it written down somewhere.

### CODE REVIEW

**Comment by peterbe** [comment]
ping @luser

**Comment by luser** [comment]
I wrote some docs:
https://github.com/peterbe/socorro/pull/13

**Comment by peterbe** [comment]
Ready?
screenshot 2015-08-18 08 29 24

**Comment by luser** [comment]
Sold!

**Pull request merged**
