### PR TITLE
Bug 1181634 - Update forced versions for correlations for Firefox cycle starting 2015-06-29

### PR DESCRIPTION
**Pull request by KaiRo-at**
This adds current aurora and nightly versions as well as all planned beta versions for this cycle.

### CODE REVIEW

**Comment by rhelmer** [comment]
@jp btw this cronjob lives on the socorroanalysis server now, which is a long-running instance that isn't part of the normal release process... we haven't worked out a good way to automatically update this yet, for now I'd suggest just logging in and updating the RPM (don't kill the instance if you can help it!)

**Comment by lonnen** [comment]
Cool. Let's do this.

**Comment by lonnen** [comment]
:fire:

**Comment by rhelmer** [comment]
@lonnen @jdotpz IIRC the `analysis` node is excluded from production pushes (it's a long-running service like the `admin` node ES, Consul, symbol-api, etc.) so you'll need to update the RPM on that node to make this change live.

We *can and should* make this node able to handle updates, it was just one of the last things to move over and didn't get as much love as the primary services. The primary challenge is that it has an EBS volume, and it has long-running jobs, so we can't safely scale up more.

**Pull request merged**
