### PR TITLE
ES_SHARDS_PER_INDEX => 10 (was 5)

### PR DESCRIPTION
**Pull request by milescrabill**
@adngdb r?

This should help allow us to add more nodes to the elasticsearch cluster, which will increase its resilience.

### CODE REVIEW

**Comment by lonnen** [comment]
I'm pretty sure this is a cosmetic configuration variable kept manually in sync with a cluster setting. It will be necessary to land after we change the cluster but will not effect the desired change on its own.

**Comment by lonnen** [comment]
Build failure looks like a temp problem in travis infra. kicking those

**Comment by lonnen** [comment]
I'm good with this. @adngdb -- thoughts?

**Comment by adngdb** [comment]
I'd rather we merge #3632 but if that is not possible (r- there, or whatever reason), I am fine with merging this and making it better later on.

**Pull request closed without merging**
