### PR TITLE
Fixes Bug 713973, Bug 1042420, Bug 1044183, Bug 913581, Bug 999923, deprecate & remove all the things

### PR DESCRIPTION
**Pull request by twobraids**
the time has come for the code removal party.  All this stuff is old, unused, unwanted and unloved.  It's time to remove them all.  Farewell, ```schema.py```

### CODE REVIEW

**Comment by peterbe** [comment]
I can't see any file that I have a relationship with that I would understand. r+

**Comment by AdrianGaudebert** [comment]
I would be in favor of simply testing this on stage. It's difficult to catch the subtle errors that this would cause in a local environment, so we might as well just merge and watch it make wonders, or open the gates of Hell. 

r+

**Comment by selenamarie** [comment]
:100: Well, 102, but close enough :dancer:

**Comment by twobraids** [comment]
blocked by the daily_url cron.

**Comment by twobraids** [comment]
@rhelmer r?

we'll have to run this in stage for a bit to ensure that I've not inadvertently killed something that we actually still use.

**Comment by rhelmer** [comment]
r+ daily_url cron is dead

**Comment by rhelmer** [comment]
We need to do a push, going to merge this after that so it has some time to bake on stage.

**Comment by lonnen** [comment]
This will break some tooling the GFX team has and really relies on.

**Comment by rhelmer** [comment]
aaand we're back to CSV being a blocker :)

**Comment by lonnen** [comment]
@twobraids had a workaround for this. It has either already landed or it was not opened, but either way he will track down the branch

**Comment by lonnen** [comment]
deleted

**Pull request merged**
