### PR TITLE
fixes bug 1122301 - upgrade requests and lxml

### PR DESCRIPTION
**Pull request by peterbe**
@AdrianGaudebert r?

We use requests for the fetching of the middleware and for django-browserid. 
We use lxml for pyquery which I think we only use for testing the django views.

### CODE REVIEW

**Comment by peterbe** [comment]
@AdrianGaudebert tests pass now.

**Comment by peterbe** [comment]
Uh. Sorry, that last comment was unnecessary. I confused this for another PR. Whatever. When time allows.

**Comment by AdrianGaudebert** [comment]
@peterbe needs rebase!

**Comment by AdrianGaudebert** [comment]
Tested locally, r+.

**Comment by peterbe** [comment]
Doing one last travis build after the rebase. Whoever sees this and travis is green, feel free to merge.

**Pull request merged**
