### PR TITLE
bug 1155504 - support apache-style userdirs for crash-analysis

### PR DESCRIPTION
**Pull request by rhelmer**
r? @jdotpz - nginx config similar to existing Apache on https://crash-analysis.mozilla.com/

### CODE REVIEW

**Comment by phrawzty** [comment]
The configuration looks fine at first glance (yay), but I'm curious as to *why* we want to do this?

**Comment by rhelmer** [comment]
> The configuration looks fine at first glance (yay), but I'm curious: why do we want to do this?

So we can move https://crash-analysis.mozilla.com/ to AWS. As I mentioned in the bug, I'd like to integrate the stuff hosted here into Socorro proper, but people still depend on some of the reports hosted there.

**Comment by rhelmer** [comment]
Oh, and I am wrong about this server even using ```UserDir``` (there are user directories stuck directly into Apache's ```DocumentRoot```

NEVERMIND :neutral_face:

**Pull request closed without merging**
